### ISSUE TITLE
Add admin, member, guest types of users

### ISSUE THREAD

**Issue by fiddleplum** [fiddleplum/211#15]
I don't know if we need more than just:
- admin (for full access via cms)
- member (for full access to a single service via cms)
- user (for normal public access)

**Comment by erickakoyama** [comment]
I feel like those levels of access are consistent with the predicted user types.

**Comment by fiddleplum** [comment]
I've added the admin and user level users with proper authentication and user/database management. I learned how to do website security properly! Our current github.io site doesn't work with server-side files, so we'll need to find another web hosting solution and then test this.

**Comment by fiddleplum** [comment]
We're keeping it on stephenhurley.me/211 until we get a more permanent location. CMS now works on mobile too.

**Comment by fiddleplum** [comment]
Completed. Any other bugs in the user accounts will be new tickets.
