### ISSUE TITLE
Multiple services at a single location need to be handled

### ISSUE THREAD

**Issue by fiddleplum** [fiddleplum/211#18]

**Comment by erickakoyama** [comment]
@fiddleplum silly question, does this mean multiple organizations operating out of one location, or one organization that falls into multiple categories?

**Comment by fiddleplum** [comment]
I think we have both situations. Definitely one organization falling into multiple categories, but on the database there are multiple organizations that have the same address.

In a list it isn't a problem, but in the mapping portion, clicking a location might need to show multiple services in its info window, rather than a single service, which might be tricky UI-wise.

**Comment by erickakoyama** [comment]
I took a look at this over the weekend, but have not made any progress yet. I may need help on this if it's okay. I am having trouble looping through the coordinates object to detect matches properly. I will keep a local branch open and continue looking at it in the meantime and work on some other tickets too.

**Comment by erickakoyama** [comment]
I'm going to look at this again tomorrow and post the code snippet in this thread, as well as publish the ticket branch.

**Comment by fiddleplum** [comment]
Okay sounds good. If it's still difficult we can get together and figure out the code.

**Comment by erickakoyama** [comment]
Ok cool. I did end up getting something I liked in the e-18 branch. I'll commit to it in the next day or so and check if you agree with the solution as well. Thanks!

**Comment by erickakoyama** [comment]
@fiddleplum okay, whenever you have a chance, the e-18 branch is ready for merge into master and I wanted to check the solution with you. I ended up pushing duplicate coordinates into the same infowindow. I have only dealt with the multiple services in one location for this issue ticket and not the service falling into multiple categories. here's the "update" function: 

`  update: function(services, serviceToHtml) {
		for(var i in Map._markers)
			Map._markers[i].setMap(null);
  		Map._markers = [];
      Map._coordinates = [];
  		Map.closeInfoWindow();
  		Map._infoWindows = [];

    for(var i in services) {
      var singleService = services[i];
      var serviceCoordinate = {};
      serviceCoordinate['coordinate'] = singleService.lat.toString() +',' + singleService.lon.toString();
      Map._coordinates.push(serviceCoordinate);
    }

    var counter = {};
    for(var j = 0; j < Map._coordinates.length; j++) {
      if (counter[Map._coordinates[j].coordinate]) {
        counter[Map._coordinates[j].coordinate].push(j);
      }
      else {
        counter[Map._coordinates[j].coordinate] = [j];
      }
    }

		for(var i in services) {
			var service = services[i];
      var singleServiceCoordinate = service.lat.toString() +',' + service.lon.toString();
			var marker = new google.maps.Marker({
				map: Map._map,
				position: new google.maps.LatLng(service.lat, service.lon),
				title: service.name
			});
			Map._markers.push(marker);
      function buildUpInfoWindowServices(array) {
        var result = '';
        array.forEach(function(current,index,array){
          result += serviceToHtml(services[current]);
        });
        return result;
      }
      var infoWindowContent = buildUpInfoWindowServices(counter[singleServiceCoordinate]);
      var infoWindow = new google.maps.InfoWindow({content: infoWindowContent});
			Map._infoWindows[service.id] = infoWindow;
			marker.infoWindow = infoWindow;
			infoWindow.marker = marker;
			marker.addListener('click', function() {
				Map.closeInfoWindow();
				this.infoWindow.open(Map._map, this);
				Map._openInfoWindow = this.infoWindow;
			});
		}
	},`

**Comment by fiddleplum** [comment]
Okay I finally merged it in and push the latest master online. I apologize that it took so long!

**Comment by fiddleplum** [comment]
I moved the updated database and new menu system that has proper categories into master, but I think it broke the multiple services in same location logic. I'll figure out what went wrong, but just letting you know in case you see master funky.

**Comment by fiddleplum** [comment]
Never mind, it works! All the services were given incorrect addresses and were resolving to the exact same lat/lon.

**Comment by erickakoyama** [comment]
Okay great! 👍

**Comment by erickakoyama** [comment]
@fiddleplum shall I close the issue and delete the branch then?

**Comment by fiddleplum** [comment]
Yeah I think so, looks good!
