### ISSUE TITLE
Use Popular CSS Framework that is good for apps

### ISSUE THREAD

**Issue by erickakoyama** [fiddleplum/211#33]

**Comment by erickakoyama** [comment]
So I would like to use a framework called Foundation that is very popular http://foundation.zurb.com/. This is responsive out of the box, and particularly app-minded.

**Comment by fiddleplum** [comment]
I don't know a whole lot about frameworks in general (a big hole in my web development experience). It looks like you can use Foundation with just vanilla html/css/js or sass or more. I'd like to stick with just the non-SASS version if that's alright with you. It looks like you can download complete, essential, or something custom, and I'll leave that up to you.

**Comment by erickakoyama** [comment]
Ok great, I agree with using the non-SASS version. For development, I would prefer to download complete CSS and then if we only end up using the grids/buttons, we can reduce it down to the essential version.
