### ISSUE TITLE
Navigation Buttons Predictable Behavior

### ISSUE THREAD

**Issue by erickakoyama** [fiddleplum/211#34]
@fiddleplum let me know if it's okay to @ message you like this. I don't want to be bothersome.
This is with regards to the menu/map button. I would like to altering the button so it only displays as a three line icon and always takes the user back to the category selection. 

Here's an example of an issue I had with the button, and this may just be me of course : ) : 
- I'm at the start page with categories
- I click on the map icon thinking it will show a map
- it shows the list view with no results
 
I think the interface gets along well without the need for that icon to change to a map. I feel like the map/list indicator takes care of that portion. 

I have one other suggestion, and this is about the map/list indicator with the up/down arrow. I really like the transition between the list and map, but the first time I saw it and other times it was very disorienting for me to see the position of the control area move from top to bottom. I think it might be good to have this button always remain in the same place, so the only movement from the user's perspective is the map/list change they triggered.

If you approve, I will start the tasks to change the behaviors. 

Cheers : )

**Comment by fiddleplum** [comment]
I think both those changes are a good ideas. Also, with the map/list transition, since the moving bar button will be gone, do you think it should still be a sliding motion as it currently is, or just a fade?

**Comment by erickakoyama** [comment]
That's a good point, I like the sliding motion as it currently is. I checked it out in chrome by dragging the #listbar above #map and #list. I felt like the transition still looked good that way.
